version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: strider-mongodb
    volumes:
      - ./mongo/db:/data/db
    ports:
      - 27000:27017
  web:
    build:
      context: .
    # image: local/strider-docker
    container_name: strider-web
    environment:
      - STRIDER_ADMIN_PASSWORD=123456
      - STRIDER_ADMIN_EMAIL=admin@strider.com
      - DB_URI=mongodb://strider-mongodb:27017/strider
    depends_on:
      - mongodb
    ports:
      - 8080:3000
    volumes:
      - ./strider:/data
  install:
    build:
      context: .
    depends_on:
      - mongodb
    volumes:
      - ./strider:/data
    entrypoint:
      - node
