version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: strider-mongodb
    volumes:
      - ./mongo/db:/data/db
  web:
    image: local/strider
    container_name: strider-web
    environment:
      - DB_URI=mongodb://strider-mongodb:27017/strider
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./strider:/data
  install:
    image: local/strider
    depends_on:
      - mongodb
    volumes:
      - ./strider:/data
  update:
    image: local/strider
    depends_on:
      - mongodb
    volumes:
      - ./strider:/data
